import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import Files from '../components/Files'
import Footer from '../components/Footer'
import Main from '../components/Main'
import NavBar from '../components/NavBar'
import styles from '../styles/Home.module.css'
import { init } from '../utils/Web3Client'

declare global {
  interface Window {
    ethereum?: any
  }
}
const Home: NextPage = () => {
  const [loading, setLoading] = useState(true)
  const [account, setAccount] = useState('0x0')
  const [fileCount, setfileCount] = useState(0)
  const [files, setFiles] = useState([])

  useEffect(() => {
    init().then(async (res) => {
      if (res && res.selectedAccount && res.contract) {
        setAccount(res.selectedAccount)
        let defileContract = res.contract
        let count = await defileContract.methods.fileCount().call()
        setfileCount(count)
        let files: any = []
        if (count > 0) {
          Array.from(Array(count).keys()).map(async (i) => {
            const file = await defileContract.methods.files(i).call()
            files = [...files, file]
          })
          setFiles(files)
        }
        setLoading(false)
      }
    })
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main>
        <Main />
        <Files />
      </main>
      <footer>
        <Footer />
      </footer>
    </div>
  )
}

export default Home
