import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import Files from '../components/Files'
import Footer from '../components/Footer'
import Loader from '../components/Loader'
import Main from '../components/Main'
import NavBar from '../components/NavBar'
import styles from '../styles/Home.module.css'
import { init } from '../utils/Web3Client'

declare global {
  interface Window {
    ethereum?: any
  }
}
const Home: NextPage = () => {
  const [loading, setLoading] = useState(false)
  const [account, setAccount] = useState('0x0')
  const [fileCount, setfileCount] = useState(0)
  const [filesToShow, setFiles] = useState<any[]>([])
  const [contract, setContract] = useState<any>()

  useEffect(() => {
    setLoading(true)
    init().then(async (res) => {
      if (res && res.selectedAccount && res.contract) {
        setAccount(res.selectedAccount)
        let defileContract = res.contract
        setContract(defileContract)
        let count = await defileContract.methods.fileCount().call()
        setfileCount(count)
        if (count > 0) {
          Array.from(Array(Number(count)).keys()).map(async (i) => {
            let file = await defileContract.methods.files(i).call()
            setFiles((prev) => [...prev, file])
          })
        }
        setLoading(false)
      }
    })
  }, [])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className="p-4 bg-slate-200 flex flex-col justify-center items-center">
        {loading && (
          <div className="w-screen h-screen z-10 bg-opacity-50 bg-slate-200  fixed top-0 left-0 flex justify-center items-center">
            <Loader />
          </div>
        )}
        <Main
          contract={contract}
          account={account}
          loading={loading}
          setLoading={setLoading}
        />
        <Files filesToShow={filesToShow} />
      </main>
      <footer>
        <Footer />
      </footer>
    </div>
  )
}

export default Home
